name: Realtime Development Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          # SECTION_NAME: ""
          # COMMIT_BY_ME: ""
          # COMMIT_MESSAGE: ""
          # COMMIT_USERNAME: ""
          # COMMIT_EMAIL: ""
          SHOW_UPDATED_DATE: "False"
          # UPDATED_DATE_FORMAT: ""
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "True"
          # IGNORED_REPOS: ""
          # SYMBOL_VERSION: ""
          # DEBUG_LOGGING: ""
